version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "pyproject.toml"
      - dependency-name: "uv.lock"
    ignore:
      - dependency-name: "requirements.txt"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
