from enum import Enum, auto

from pydantic import BaseModel


class ResponseType(Enum):
    """Types of configurations generated by the LLM"""

    COMPOSE_FILE = auto()
    ENV_FILE = auto()


class LLMResponse(BaseModel):
    """Generated configuration LLM response"""

    type: ResponseType
    name: str
    data: str
