"""LLM Generator Models Definitions

These data types are abstractions of what a specialized model could return
"""

from enum import Enum, auto

from pydantic import BaseModel


class ResponseType(Enum):
    """Types of configurations generated by the LLM"""

    NO_RESPONSE = auto()
    ENV_FILE = auto()
    COMPOSE_FILE = auto()


class LLMResponse(BaseModel):
    """Generated configuration LLM response"""

    type: ResponseType
    name: str
    data: str
