services:
  keycloack:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: devops-final-keycloack
    command: ["start-dev"]
    env_file:
      - .env.keycloak
    ports:
      - 8080:8080
    networks:
      - devops-final

networks:
  devops-final:
    driver: bridge